name: Selenium UI Tests

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run-selenium-tests]
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-selenium-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout Selenium Tests Repo
        uses: actions/checkout@v3

      - name: Checkout React Portfolio Repo
        uses: actions/checkout@v3
        with:
          repository: logangarbacki/react-portfolio-website
          token: ${{ secrets.PORTFOLIO_REPO_PAT }}
          path: portfolio

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore ./SeleniumTestFramework.csproj

      - name: Build Selenium Project
        run: dotnet build --no-restore ./SeleniumTestFramework.csproj

      - name: Run Selenium Tests
        run: dotnet run --project ./SeleniumTestFramework.csproj